name: Test

on:
  push: {}
  workflow_dispatch: {}

jobs:
  tests:
    uses: coinlist/.github/.github/workflows/docker_on_push.yml@main
    with:
      image: ${{ github.event.repository.name }}
      tag: ${{ github.sha }}
