name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    uses: coinlist/.github/.github/workflows/docker_on_release.yml@main
    with:
      image: ${{ github.event.repository.name }}
      tag: latest
