name: Terraform plan

on:
  push:
    branches-ignore:
      - main
    paths:
      - "terraform/**"

jobs:
  release:
    uses: coinlist/.github/.github/workflows/terraform_on_push.yml@main
    with:
      terraform-version: 1.1.9
