name: Release Docker project

on:
  workflow_call:
    inputs:
      image:
        description: Image name
        type: string
        required: true
      tag:
        description: Image tag
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
      - name: Get ECR password (temporary)
        id: ecr-password
        run: echo "::set-output name=password::$(aws ecr get-login-password)"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          username: AWS
          password: ${{ steps.ecr-password.outputs.password }}
          registry: ${{ steps.ecr-login.outputs.registry }}
          repository: ${{ inputs.image }}
          tags: coinlist/${{ inputs.image }}:${{ inputs.tag }}
          add_git_labels: true
          push: true
      - name: Logout from Amazon ECR
        if: always()
        run: docker logout ${{ steps.ecr-login.outputs.registry }}
