name: Test

on:
  workflow_call:
    inputs:
      image:
        description: Image name
        type: string
        required: true
      tag:
        description: Image tag
        type: string
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: coinlist/${{ inputs.image }}:${{ inputs.tag }}
      - name: Run tests
        run: |
          docker exec -t coinlist/${{ inputs.image }}:${{ inputs.tag }} make test
