name: Code style and test
concurrency:
  group: on_push
  cancel-in-progress: true

on:
  push: {}
  workflow_dispatch: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '2.7'
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake