name: Test

on:
  workflow_call: {}

jobs:
  build-test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          target: test
          tags: ${{github.repository}}_test
          outputs: type=docker,dest=/tmp/test-image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-image
          path: /tmp/test-image.tar
          retention-days: 1
  unit-test:
    needs: [build-test-image]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: test-image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/test-image.tar
          docker image ls -a
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unit Test ✅
        run: docker compose --env-file /dev/null run --rm test
