name: Test
concurrency:
  group: on_push
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: coinlist/${{ inputs.image }}:latest
      - name: Run tests
        run: |
          docker exec -t coinlist/${{ inputs.image }}:latest make test
