name: Terraform plan and apply

on:
  workflow_call:
    inputs:
      terraform-version:
        description: Terraform version
        type: string
        default: "1.1.9"
        required: false
    secrets:
      TF_API_TOKEN:
        description: Terraform API token
        required: true

jobs:
  terraform:
    name: Terraform plan and apply
    env:
      TF_VAR_name: common
      TF_VAR_environment: proto
      TF_VAR_region: us-west-2
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        id: setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform-version }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: |
          terraform init

      - name: Terraform Validate
        id: validate
        run: |
          terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color -input=false -var-file terraform.tfvars

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: |
          exit 1

      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -auto-approve -var-file terraform.tfvars
